name: Release
on: [push]

jobs:
release:
  name: Release package
  runs-on: ubuntu-18.04
  steps:
  - name: Checkout
      uses: actions/checkout@v1
  - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
      node-version: 12
  - name: Release
      env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn semantic-release
